# Generated by Django 4.0.5 on 2022-06-10 15:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_blog_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
